services:
  postgresql:
    image: postgres:14.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mood-tracker
    healthcheck:
      test: [ "CMD", "psql", "postgresql://user:password@localhost:5432/mood-tracker", "-c", "select 1;" ]
      interval: 5s
      timeout: 5s
      retries: 3
