server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false

spring:
  application:
    name: mood-tracker
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "\"mood-tracker\""
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1260000
  flyway:
    schemas: mood-tracker

mood_tracker:
  telegram:
    bot:
      token: ${TELEGRAM_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health
